# Generated by Django 5.1 on 2024-09-03 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_user_is_admin_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
