# Generated by Django 5.1 on 2024-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0004_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
